spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.5.37/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null

server:
  context-path: /sell

wechat:
  mpAppId:  wx6e72da652d4a8dd1
  mpAppSecret: a20553da148998615b4cfe678f415feb

wechatUrl:
  root: http://sell.com/wechat/

#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file:  /Users/melon/log/sell/sell.log
#  level: debug

